In [ ]:
import numpy as np
import sys

In [ ]:
data1 = [3.2, 5, 7, 9.6]   # list
arr1 = np.array(data1)    # array

In [ ]:
arr1

array([3.2, 5. , 7. , 9.6])

In [ ]:
data2 = (2.3, 5, 8, 96, 125.3)     # list
arr2 = np.array(data2)             # array

In [ ]:
arr2.ndim        # massiv o'lchovini aniqlash

1

In [ ]:
data3 = [[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]]     # list ichidagi list  (nested list)
arr3 = np.array(data3)         # array

In [ ]:
arr3.ndim    # massiv o'lchovini aniqlash

2

In [ ]:
data4 = [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]]        # list list ichidagi list
arr4 = np.array(data4)

In [ ]:
arr4

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [ ]:
arr4.shape   # qator va ustunlar sonini ko'rsatadi (q, u)

(1, 3, 5)

In [ ]:
arr4.size    # arry4 ning elementlar sonini ko'rsatadi

15

In [ ]:
arr5 = np.zeros((3, 5))  # massivni 3qator 5 ustunni 0 bilan to'ldirib beradi
arr5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr6 = np.ones(shape = (2, 4))    # arrage ni 2qator 4 ustinni 1 bilan to'ldirib beradi
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr7 = np.arange(10, 101, 5)    #berilgan oraliqdagi sonlarni qaytaradi boshlangichdan oxirigacha 5 son oralatib
arr7

In [ ]:
array1 = np.array([])            # bo'sh massiv yaratish
print(array1, type(array1))

[] <class 'numpy.ndarray'>


In [ ]:
array2 = np.array([1,2,3,4,5,6])
print(array2, type(array2))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [ ]:
my_list = list(range(100000)) # python list 0~99999 -->Normal
my_array = np.array(range(100000)) # numpy array(massiv) 0~99999 --> Vektorlashgan
my_array

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [ ]:
%time for _ in range(10): [x*2 for x in my_list] # Normal

CPU times: user 106 ms, sys: 14.7 ms, total: 121 ms
Wall time: 133 ms


In [ ]:
%time for _ in range(10): my_array*2 # Vektorlashgan

CPU times: user 2.86 ms, sys: 0 ns, total: 2.86 ms
Wall time: 2.88 ms


In [ ]:
72.2 / 2.62      #numpy kutubxonasi python listdan 27 marotaba tezroq ishlar ekan

27.557251908396946

In [ ]:
sizeof_my_list = sys.getsizeof(1) * len(my_list)     # normal ~~~ xotira


In [ ]:
sizeof_numpy_array = my_array.itemsize * my_array.size      #vektorlashgan 


In [ ]:
np_array = ([1, 2, 3, 4, 5])    #numpy array
py_list = list(np_array)        #python list
type(py_list)

list

In [ ]:
#maxsus numpy massiv tasodifiy qiymatlarga ega massiv
arr_rand = np.random.randint(low=1, high=10, size=(3,2))
arr_rand

In [ ]:
#har bir ustun turli qiymatlarga ega bulishi
rand_arr = np.random.randint(low=[10,100], high=[20,200], size=(2,2))
rand_arr

array([[ 14, 115],
       [ 15, 109]])

In [ ]:
arr = np.array([1,2,3,4,5], dtype=np.int16)    #int16
arr.dtype

dtype('int16')

In [ ]:
arr_int = np.array([1,3,5,7,9,11])    #hech qanday dtype berilmasa u uzi int64 yoki float64 deb oladi
float_arr = arr_int.astype(np.float16)
float_arr.dtype

dtype('float16')

In [ ]:
arr_float1 = np.array([1.2, 5.3, 8.6, 7.2, 6.3])     #float array
arr_int1 = arr_float1.astype(np.int8)                #int array
arr_int1

array([1, 5, 8, 7, 6], dtype=int8)