In [1]:
import numpy as np

In [ ]:
arr = np.arange(5, 101, 5)      #arange funksiyasi orqali
arr[2]      #2-indeksga murojaat qildik

15

In [ ]:
arr[3:5]    # 3dan 5gacha elementlarni kesib olib beradi

array([20, 25])

In [ ]:
sliced_arr = arr[3:5]     #kesib olish
sliced_arr[:] = 0    # [:] bu belgi hammasi degani yani hammasini 0 ga aylantiradi
sliced_arr          # ehtiyot bolib ishlatish kerak bu o'zgartirish asosiy arryga ham tasir qiladi

array([0, 0])

In [ ]:
arr1 = np.arange(10, 100, 10)      #array yaratib oldik
sliced_arr1 = arr1[3:5].copy()     #arraydan nusxa oldik
sliced_arr1[:] = 0                 #nusxa olingan arrayni nolga o'zgartirdik
sliced_arr1                        # bu usulda asosiy massiv ozgrmadi

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])              #2 o'lchovli array

In [ ]:
arr2d[2,1]    # 2d arrayga indeks orqali shu tartibda kesib olinadi


8

In [ ]:
sl_arr2d = arr2d[1:3, 1:3]   #2d massivning 2-3-elementlarini kesib oldim
sl_arr2d

array([[5, 6],
       [8, 9]])

In [ ]:
arr3d =  np.array([[[0,1,2],
    [3,4,5],
    [6,7,8]],

    [[9,10,11],
     [12,13,14],
     [15,16,17]],

    [[18,19,20],
     [21,22,23],
     [24,25,26]]
])
arr3d.ndim

3

In [ ]:
arr3d[1][1:3, 0:3]      #Biz bu yerda ikki o'lchamli arrayga otib oldik va keyin kesib oldik

array([[12, 13, 14],
       [15, 16, 17]])

In [ ]:
names = np.array(['Axror', 'Javlon', 'Jamshid', 'Javlon', 'Diyor'])      #ismlar array
names

array(['Axror', 'Javlon', 'Jamshid', 'Javlon', 'Diyor'], dtype='<U7')

In [ ]:
data = np.random.randn(5,5)    # 7ga 4 massiv yaratib oldik
data

array([[-0.73551181,  1.01047787, -0.63135238,  0.91943583,  0.1241235 ],
       [-0.21613181,  1.58825766,  0.16522089, -0.02755058,  1.73657393],
       [ 2.05040505, -0.80385553, -1.5995864 ,  1.82104926,  0.02867803],
       [-1.53153811, -1.586858  , -0.80448714, -0.81198533, -1.53111288],
       [-0.08779354,  1.73561354, -0.40022957, -1.68792174,  1.36274439]])

In [ ]:
names == 'Javlon'         #Javlon bor yoki yoqligigni tekshiradi

array([False,  True, False,  True, False])

In [ ]:
data[names=='Javlon', 2:]          # Javlonga tegishli malumotlar

array([[ 0.16522089, -0.02755058,  1.73657393],
       [-0.80448714, -0.81198533, -1.53111288]])

In [ ]:
mask = (names == "Javlon") | (names == "Diyor")   # "|" or (yoki)
mask

array([False,  True, False,  True,  True])

In [ ]:
data[mask]     # Diyor va Javlonga tegishli datalarni kesib oldik

array([[-0.21613181,  1.58825766,  0.16522089, -0.02755058,  1.73657393],
       [-1.53153811, -1.586858  , -0.80448714, -0.81198533, -1.53111288],
       [-0.08779354,  1.73561354, -0.40022957, -1.68792174,  1.36274439]])

In [ ]:
arrt =  np.arange(6).reshape(3, 2)             #A massiv : Elementlari 0~6 gacha , shape (3, 2)
arrt

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arrt.T              #   A massivning Trasnpose ko'rinishi beradi

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
arrt.swapaxes(1, 0)              # A massivning Transpose ko'rinishi beradi

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
np.dot(arrt, arrt.T)             #AA^T hosil bo'lgan massiv

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

In [ ]:
                                                                      ### UNIVERSAL FUNKSIYALAR

In [ ]:
arruniversal = np.arange(10)           # 0~10gacha arraylar to'plami
np.sqrt(arruniversal)            #berilgan barcha arraylardan kvadrat ildiz oladi

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.square(arruniversal)        # barcha arraylarni kvadratga oshirdi

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
np.exp(arruniversal)        #barcha elementlarni exponentini qaytaradi    e^n

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.log(arruniversal)        #elementlarni logarifmini hisoblaydi log^e

<ipython-input-12-b04ef8b2f5fd>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arruniversal)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
arrmod = np.random.randn(6)              # berilgan massivning butun va haqiqiy qismini ajratib beradi 2ta massivga
qoldiq, butun = np.modf(arrmod)
print(qoldiq)
print(butun)
print(arrmod)

[ 0.79946371  0.95139089 -0.31796271 -0.46338586 -0.07052537 -0.32848768]
[ 0.  0. -0. -0. -0. -1.]
[ 0.79946371  0.95139089 -0.31796271 -0.46338586 -0.07052537 -1.32848768]


In [ ]:
np.sign(arrmod)            # berilgan massiv elementlari manfiy bolsa -1 musbat bolsa 1 qiymat qaytaradi

array([ 1.,  1., -1., -1., -1., -1.])

In [ ]:
np.isnan(arrmod)              # massiv elementlari NaN ma'lumot bolsa TRUE aksincha esa FALSE qaytaradi      NaN-(not a number) raqam emas

array([False, False, False, False, False, False])

In [ ]:
                                             # Binary funksiyalr (2ta argument qabul qiluvchi)

In [ ]:
arr3 = np.random.randn(5)
arr4 = np.random.randn(5)
np.add(arr3, arr4)                   # 2ta massivning mos elementlarini qushadi
arr3 + arr4                 #bu ham shu ishni qiladi

array([-1.00163168,  0.94947789, -0.43243796, -0.7560059 ,  1.41833066])

In [ ]:
np.multiply(arr3, arr4)             #2ta massivning mos elementlarini kupaytiradi

array([-0.69053842,  0.05389442, -0.1522934 ,  0.06421295,  0.41504809])

In [ ]:
np.maximum(arr3, arr4)         #2ta array elementlarini taqqoslab kattasini qaytaradi

array([ 0.46941863,  0.88884358,  0.22992455, -0.09751537,  1.00558966])

In [ ]:
#Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])   #xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])   #yarr
#shart
cond = np.array([True, False, True, True, False])
#where funksiyasi
result = np.where(cond, xarr, yarr)        # cond==True : xarr elementi, cond==False : yarr elementi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
arrwh = np.random.randn(4, 4)
results = np.where(arrwh<0, -2, 2)       # arr ning manfiy elementlarini -2 ga musbat elementlarin esa 2 ga almashitirish
results

array([[ 2, -2,  2,  2],
       [-2,  2, -2,  2],
       [ 2,  2, -2,  2],
       [ 2, -2, -2, -2]])

In [ ]:
arrar1 = np.arange(6).reshape(2, 3)            # 0~6 gacha 2 3 massiv
arrar2 = np.arange(6, 12).reshape(2, 3)        # 6~12 gacha 2 3 massiv
arrar2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arrar1 + arrar2            # 1-va 2-massivlarni qo'shish
arrar1 * arrar2            # 1-va 2- massivlarni ko'paytirish
arrar1 / arrar2            # 1-va 2- massivlarni  bo'lish
arrar1 - arrar2            # 1-va 2- massivlarni  ayirish
arrar1 ** 2                # 1-massiv elementlarini kvadratga oshiradi   (square)
arrar2 ** 0.5              # 1-massiv elementlarini kvadrat ildizi    (sqrt  )

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

In [ ]:
arrsum = np.random.randn(5, 4)              #(5:4) massiv
arrsum

array([[-0.85351184, -0.20958757, -0.23195173,  1.24919904],
       [ 0.04378211,  0.33606289,  0.36815237, -0.86226373],
       [ 0.68188753, -2.8311622 , -2.07936377, -1.33224903],
       [-1.25466799, -0.48465904,  0.2873312 ,  0.68872267],
       [-0.68755101, -0.89032083,  0.65277931, -0.4878058 ]])

In [ ]:
arrsum.sum()             # barcha arrays yig'indisi
np.sum(arrsum)          #arrsumning barcha elementlarining yig'indisini hisoblab beradi

-7.897177422646729

In [ ]:
arrsum.sum(axis=1)            #qator yig'indi
arrsum.sum(axis=0)            #ustun yig'indi

array([-0.0458521 , -0.11426636, -5.56088747, -0.76327316, -1.41289833])

In [ ]:
#sodda ma'lumot
data = np.arange(5)       # 0~5gacha massiv
mean = np.sum(data)/len(data)

#numpy mean
np.mean(data)           #1-usul      O'rtacha arifmetikni hisoblab beradi
data.mean()             #2-usul      tepadagi bn bir xil


np.mean(arrsum, axis=1)           #qator buyicha ortacha qiymatni qaytaradi

array([-0.01146302, -0.02856659, -1.39022187, -0.19081829, -0.35322458])

In [ ]:
#cumsum metodi bu yigindilab boradigan ygindidir
data
data.cumsum()              #1-usul
np.cumsum(data)            #2-usul

array([ 0,  1,  3,  6, 10])

In [ ]:
arr_sort = np.random.randn(5)    # 4 ta taxminiy elementlardan tashkil topgan massiv    
# 1-usul
sorted_arr = np.sort(arr_sort)      # berilgan massivdan nusxa olib tartiblash yani b-n massiv o'zgarmaydi

# 2-usul
arr_sort.sort()          # b-n massivning uzida tartiblash yani b-n massiv o'zgaradi

# teskari tartiblash
rev_arr = -np.sort(-arr_sort)             # b-n massivni teskari tartiblash

# 2d massivlarni tartiblash
arr2d = np.random.randn(2, 4)         # (2:4) massiv
# axis = 0 --> Qator
row_str = np.sort(arr2d, axis=0)    
row_str   
# axis = 1 --> Ustun
col_str = np.sort(arr2d, axis=1)
col_str

array([-0.13224825,  1.60148686,  1.70856176, -1.21615687, -0.51469336])

In [ ]:
# Takrorlanmas amallar
names = np.array(['Sarvar', 'Abdurahmon', 'Hasan',  'Temur', 'Sarvar', 'Temur'])
np.unique(names)              # names dagi takrorlanmas elementlarni qaytaradi (takrorlansa ham faqat bittasini qabul qiladi)

# in1d usuli
arr1d = np.array([6, 0, 0, 3, 2, 5, 6])
arr2d = np.array([0, 2, 3])
np.in1d(arr1d, arr2d)          # arr2 dagi elementlarni arr1 da mavjudligini tekshirish

# setdiff1d usuli
np.setdiff1d(arr1d, arr2d)         # names1 massivining names2 massividagi takrorlanmas qismini qaytaradi

array([5, 6])

In [ ]:
a = np.array([[1,2],[3,4]])
# b = np.arange(0, 10, 2)
# c = a+ b
# c = a + b
print(a.itemsize)
# print(a.ndim)
# a = range(2, 9)
# map(lambda x, y: x ** y, a, reversed(a))

8
