
# ![Imgur](https://imgur.com/Dmyouta.png)
# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np


<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>

In [2]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [5]:
massiv = [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr = np.array(massiv)
arr.ndim

1

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



[Текст ссылки](https://)`💡Ishora` np.zeros

In [6]:
zeros = np.zeros(shape=(9,9))
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [9]:
data = [[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]]
arr2 = np.array(data)
print(f"Size: {arr2.size}")
print(f"Itemsize: {arr2.itemsize}")

Size: 10
Itemsize: 8


#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [14]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [16]:
massiv = np.zeros(12)
massiv[5] = 1
massiv

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [17]:
vektor = np.arange(20, 60)
vektor

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [20]:
teskari = np.flip(vektor) # 1-usul FLIP metodi orqali
teskari
teskari1 = vektor[::-1]     # 2-usul orqaga sanash orqali
teskari1

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
       42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [21]:
matritsa = np.arange(12, 21).reshape(3, 3)
matritsa

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [24]:
list = [3, 7, 0, 0, 9, 0]
arr = np.array(list)
zero = np.nonzero(arr)
zero

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [29]:
massiv = np.random.random((2,2,2))
massiv

array([[[0.86803755, 0.59945268],
        [0.42889087, 0.17729234]],

       [[0.53249629, 0.6112692 ],
        [0.48444532, 0.91641176]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [33]:
massiv = np.random.rand(9,9)
min = np.min(massiv)
max = np.max(massiv)
print(f"Eng kichik son: {min}")
print(f"Eng katta son: {max}")

Eng kichik son: 0.0007377647249436903
Eng katta son: 0.9837765778167417


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [34]:
# ❌ Men misolni tushinmadim shuning uchun ishlamadim

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [40]:
matritsa1 = np.arange(0, 18).reshape(6,3)
matritsa2 = np.arange(100, 112).reshape(3,4)
sum = np.dot(matritsa1, matritsa2)
sum

array([[ 320,  323,  326,  329],
       [1256, 1268, 1280, 1292],
       [2192, 2213, 2234, 2255],
       [3128, 3158, 3188, 3218],
       [4064, 4103, 4142, 4181],
       [5000, 5048, 5096, 5144]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [42]:
# ❌ Men misolni tushinmadim shuning uchun ishlamadim

from numpy import *
print(sum(range(5),-1))
print(sum(range(5),-1))

10
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [45]:
a = np.array([1,2])
b = np.array([4,5])
print(a>=b)
print(a<b)
print(a<=b)

[False False]
[ True  True]
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [46]:
# ❌ Men misolni tushinmadim shuning uchun ishlamadim
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-46-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-46-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [50]:
a = np.arange(1,6)
b = np.arange(2, 7)
natija = np.intersect1d(a, b)
natija

array([2, 3, 4, 5])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [56]:
random_array = np.random.randn(10)
foiz = random_array[random_array > 0]
floor = np.floor(random_array[random_array>0])
astype = random_array[random_array > 0].astype(int)
trunc = np.trunc(random_array[random_array > 0])

print(f"Foiz: {foiz}")
print(f"Floor: {floor}")
print(f"Astype: {astype}")
print(f"Trunc: {trunc}")

Foiz: [1.73622699 1.27450648 0.45999873 0.79282166 0.31287223 0.5495463
 1.2527684  1.53838776]
Floor: [1. 1. 0. 0. 0. 0. 1. 1.]
Astype: [1 1 0 0 0 0 1 1]
Trunc: [1. 1. 0. 0. 0. 0. 1. 1.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [57]:
matrix = np.arange(3).reshape(3, 1) + np.arange(3)
matrix

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [60]:
vektor = np.random.rand(10)
sort = np.sort(vektor)
print(f"Tasodifiy vektor: {vektor}")
print(f"O'sish tartibidagi vektor: {sort}")

Tasodifiy vektor: [0.61257825 0.19809565 0.95681653 0.28514791 0.74757969 0.22575122
 0.17383618 0.32084966 0.6708034  0.88929869]
O'sish tartibidagi vektor: [0.17383618 0.19809565 0.22575122 0.28514791 0.32084966 0.61257825
 0.6708034  0.74757969 0.88929869 0.95681653]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [62]:
a = np.random.rand(3, 3)
b = np.random.rand(3, 3)
allclose = np.allclose(a, b)
equal = np.array_equal(a, b)

print(f"Allclose: {allclose}")
print(f"Equal: {equal}")

Allclose: False
Equal: False


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [65]:
kupaytma1 = np.dot(a, b)

print(f"Dot: {kupaytma1}")

Dot: [[0.58732717 0.88086677 0.60369869]
 [1.15774024 1.85664045 1.14625298]
 [0.39083796 0.76978264 0.63105264]]


#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [69]:
#  6-misol bilan bir xil
massiv = np.random.random(5)
argmax = np.argmax(massiv)
natija = massiv[argmax] = 0
print(f"Oddiy massiv: {massiv}")
print(f"Eng katta qiymat: {argmax}")
print(f"O'zgartirilgan massiv: {natija}")

Oddiy massiv: [0.79373854 0.57005544 0.81598682 0.         0.29116692]
Eng katta qiymat: 3
O'zgartirilgan massiv: 0


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [71]:
bugun = np.datetime64('today', 'D')
kecha = bugun - np.timedelta64(1, 'D')
ertaga = bugun + np.timedelta64(1, 'D')

print(f"Bugun sana: {bugun}")
print(f"Ertaga sana: {ertaga}")
print(f"Kechagi sana: {kecha}")

Bugun sana: 2023-12-15
Ertaga sana: 2023-12-16
Kechagi sana: 2023-12-14


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [73]:
yanvar = np.arange('2016-01', '2016-02', dtype='datetime64[D]')

print(f"2016 yil yanvar oyidagi sanalar: \n{yanvar}")



2016 yil yanvar oyidagi sanalar: 
['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [74]:
# Bu misol ishlangan 19-misol bilan bir xil yozishga vaqt sarflagim kelmadi

random_array = np.random.randn(10)
foiz = random_array[random_array > 0]
floor = np.floor(random_array[random_array>0])
astype = random_array[random_array > 0].astype(int)
trunc = np.trunc(random_array[random_array > 0])

print(f"Foiz: {foiz}")
print(f"Floor: {floor}")
print(f"Astype: {astype}")
print(f"Trunc: {trunc}")


Foiz: [0.06980457 0.00608187 0.01016693 1.05249295]
Floor: [0. 0. 0. 1.]
Astype: [0 0 0 1]
Trunc: [0. 0. 0. 1.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [76]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.array([7, 8, 9])

reduce = np.add.reduce([array1, array2, array3])

print("Array 1:", array1)
print("Array 2:", array2)
print("Array 3:", array3)
print("Natija:", reduce)


Array 1: [1 2 3]
Array 2: [4 5 6]
Array 3: [7 8 9]
Natija: [12 15 18]


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

IndexError: ignored

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [83]:

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
qadamla = (a.itemsize, a.itemsize)
b = np.lib.stride_tricks.as_strided(a, shape=(11, 4), strides=qadamla)


print("Array a:")
print(a)

print("\nArray b:")
print(b)


Array a:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Array b:
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [84]:
# Bu misolni ishlolmadim

Arbitrary Array:
[1 2 3 2 4 5 3 6 2 7 2 8 9 1 2]

Counts of Each Value:
[0 2 5 2 1 1 1 1 1 1]

Most Common Value(s):
2


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`